- name: Coping mongodb repo file 
  ansible.builtin.copy:
    src: mongod.repo 
    dest: /etc/yum.repos.d/mongodb.repo 
    remote_src: yes

- name: Install Mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: present

- name: Update Listen IP address from 127.0.0.1 to 0.0.0.0 in the config file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting the nginx service
  ansible.builtin.service:
    name: mongod
    state: started # for db's it should not be restart. always started
    enabled: yes


- name: Download and extract
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/mongodb/archive/main.zip"
    dest: /tmp
    remote_src: yes
  
- name: Create a new schema with name acme in test database
  community.mongodb.mongodb_shell:
    file: /tmp/mongodb-main/{{item}}.js
    idempotent: yes # once schema is loaded, it allow further changed
  loop:
      - user
      - catalogue